# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x16servicorn.core.grpc.v1\"%\n\x06Header\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xb9\x01\n\x0eRequestContext\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61ller\x18\x02 \x01(\t\x12\x12\n\ntimeout_ms\x18\x03 \x01(\x05\x12\x42\n\x06\x65xtras\x18\x04 \x03(\x0b\x32\x32.servicorn.core.grpc.v1.RequestContext.ExtrasEntry\x1a-\n\x0b\x45xtrasEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x85\x01\n\x0bHttpRequest\x12\x13\n\x0bhttp_method\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x14\n\x0cquery_string\x18\x03 \x01(\t\x12/\n\x07headers\x18\x04 \x03(\x0b\x32\x1e.servicorn.core.grpc.v1.Header\x12\x0c\n\x04\x62ody\x18\x05 \x01(\x0c\"*\n\tErrorInfo\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"d\n\x0eResponseResult\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12/\n\x07headers\x18\x02 \x03(\x0b\x32\x1e.servicorn.core.grpc.v1.Header\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\"\x80\x01\n\x0fGrpcCallRequest\x12\x34\n\x07request\x18\x01 \x01(\x0b\x32#.servicorn.core.grpc.v1.HttpRequest\x12\x37\n\x07\x63ontext\x18\x02 \x01(\x0b\x32&.servicorn.core.grpc.v1.RequestContext\"|\n\x10GrpcCallResponse\x12\x36\n\x06result\x18\x01 \x01(\x0b\x32&.servicorn.core.grpc.v1.ResponseResult\x12\x30\n\x05\x65rror\x18\x02 \x01(\x0b\x32!.servicorn.core.grpc.v1.ErrorInfo2h\n\x07Gateway\x12]\n\x08GrpcCall\x12\'.servicorn.core.grpc.v1.GrpcCallRequest\x1a(.servicorn.core.grpc.v1.GrpcCallResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTCONTEXT_EXTRASENTRY']._loaded_options = None
  _globals['_REQUESTCONTEXT_EXTRASENTRY']._serialized_options = b'8\001'
  _globals['_HEADER']._serialized_start=41
  _globals['_HEADER']._serialized_end=78
  _globals['_REQUESTCONTEXT']._serialized_start=81
  _globals['_REQUESTCONTEXT']._serialized_end=266
  _globals['_REQUESTCONTEXT_EXTRASENTRY']._serialized_start=221
  _globals['_REQUESTCONTEXT_EXTRASENTRY']._serialized_end=266
  _globals['_HTTPREQUEST']._serialized_start=269
  _globals['_HTTPREQUEST']._serialized_end=402
  _globals['_ERRORINFO']._serialized_start=404
  _globals['_ERRORINFO']._serialized_end=446
  _globals['_RESPONSERESULT']._serialized_start=448
  _globals['_RESPONSERESULT']._serialized_end=548
  _globals['_GRPCCALLREQUEST']._serialized_start=551
  _globals['_GRPCCALLREQUEST']._serialized_end=679
  _globals['_GRPCCALLRESPONSE']._serialized_start=681
  _globals['_GRPCCALLRESPONSE']._serialized_end=805
  _globals['_GATEWAY']._serialized_start=807
  _globals['_GATEWAY']._serialized_end=911
# @@protoc_insertion_point(module_scope)
